### PR TITLE
Added catapult-rest 0.7.15

### PR DESCRIPTION
**Pull request by dgarcia360**

### CODE REVIEW

**Comment by rg911** [comment]
Also after generated js files using openapi-generator, noticed that some docs are garbled. E.g. in `accountRoutesApi.js - incomingTransactionsWithHttpInfo(publicKey, opts)` , the doc shows `* @param {String} opts.ordering The ordering criteria. * &#x60;&#x60;-id&#x60;&#x60; - Descending order by id. * &#x60;&#x60;id&#x60;&#x60; - Ascending order by id.  (default to &#39;-id&#39;)`

**Comment by dgarcia360** [comment]
@rg911 Thanks for the review,

**Account properties:**  Added ``publicKeys`` in the request body.

**Formatting error:** It seems open api generator doesn't like special characters. I have deleted most of them, let me know if you detect some additional formatting error.

**Comment by dgarcia360** [comment]
@rg911 I have updated the swagger file adding transaction types and fixing the request body bug. Let me know if it works for you.

**Comment by rg911** [comment]
@dgarcia360 

> @rg911 I have updated the swagger file adding transaction types and fixing the request body bug. Let me know if it works for you.

Works perfectly. well done mate! 👍

**Pull request merged**
